<?php

return [
    "LINE_PAY_CHANNEL_ID" => env("LINE_PAY_CHANNEL_ID"),
    "LINE_PAY_CHANNEL_SECRET"  => env("LINE_PAY_CHANNEL_SECRET"),
    "LINE_PAY_CONFIRM_URL" => env("LINE_PAY_CONFIRM_URL"),
    "LINE_PAY_CANCEL_URL" => env("LINE_PAY_CANCEL_URL"),
    "LINE_PAY_SANDBOX" => env("LINE_PAY_SANDBOX")
];
